create table lightpriorityevent
(
    id double precision,
    topic_prefix varchar(255),
    topic_version varchar(255),
    journey_type varchar(255),
    is_ongoing boolean,
    event_type varchar(255),
    mode varchar(255),
    owner_operator_id smallint,
    vehicle_number integer,
    unique_vehicle_id varchar(255),
    route_id varchar(255),
    direction_id smallint,
    headsign varchar(255),
    journey_start_time time,
    next_stop_id varchar(255),
    geohash_level smallint,
    topic_latitude double precision,
    topic_longitude double precision,
    desi varchar(255),
    dir smallint,
    oper smallint,
    veh integer,
    tst timestamp with time zone,
    tsi bigint,
    spd double precision,
    hdg smallint,
    lat double precision,
    long double precision,
    acc double precision,
    dl integer,
    odo double precision,
    drst boolean,
    oday date,
    jrn integer,
    line smallint,
    start time,
    loc varchar(255),
    stop integer,
    route varchar(255),
    occu smallint,
    received_at timestamp with time zone,
    uuid uuid,
    tlp_requestid integer,
    tlp_requesttype varchar(255),
    tlp_prioritylevel varchar(255),
    tlp_reason varchar(255),
    tlp_att_seq integer,
    tlp_decision varchar(255),
    sid integer,
    signal_groupid integer,
    tlp_signalgroupnbr integer,
    tlp_line_configid integer,
    tlp_point_configid integer,
    tlp_frequency integer,
    tlp_protocol varchar(255),
    seq smallint,
    dr_type smallint,
    version bigint
);

alter table lightpriorityevent owner to postgres;

create table otherevent
(
    id double precision,
    topic_prefix varchar(255),
    topic_version varchar(255),
    journey_type varchar(255),
    is_ongoing boolean,
    event_type varchar(255),
    mode varchar(255),
    owner_operator_id smallint,
    vehicle_number integer,
    unique_vehicle_id varchar(255),
    route_id varchar(255),
    direction_id smallint,
    headsign varchar(255),
    journey_start_time time,
    next_stop_id varchar(255),
    geohash_level smallint,
    topic_latitude double precision,
    topic_longitude double precision,
    desi varchar(255),
    dir smallint,
    oper smallint,
    veh integer,
    tst timestamp with time zone,
    tsi bigint,
    spd double precision,
    hdg smallint,
    lat double precision,
    long double precision,
    acc double precision,
    dl integer,
    odo double precision,
    drst boolean,
    oday date,
    jrn integer,
    line smallint,
    start time,
    loc varchar(255),
    stop integer,
    route varchar(255),
    occu smallint,
    received_at timestamp with time zone,
    uuid uuid,
    seq smallint,
    dr_type smallint,
    version bigint
);

alter table otherevent owner to postgres;

create table stopevent
(
    id double precision,
    topic_prefix varchar(255),
    topic_version varchar(255),
    journey_type varchar(255),
    is_ongoing boolean,
    event_type varchar(255),
    mode varchar(255),
    owner_operator_id smallint,
    vehicle_number integer,
    unique_vehicle_id varchar(255),
    route_id varchar(255),
    direction_id smallint,
    headsign varchar(255),
    journey_start_time time,
    next_stop_id varchar(255),
    geohash_level smallint,
    topic_latitude double precision,
    topic_longitude double precision,
    desi varchar(255),
    dir smallint,
    oper smallint,
    veh integer,
    tst timestamp with time zone,
    tsi bigint,
    spd double precision,
    hdg smallint,
    lat double precision,
    long double precision,
    acc double precision,
    dl integer,
    odo double precision,
    drst boolean,
    oday date,
    jrn integer,
    line smallint,
    start time,
    loc varchar(255),
    stop integer,
    route varchar(255),
    occu smallint,
    received_at timestamp with time zone,
    uuid uuid,
    seq smallint,
    dr_type smallint,
    version bigint
);

alter table stopevent owner to postgres;

create table unsignedevent
(
    id double precision,
    topic_prefix varchar(255),
    topic_version varchar(255),
    journey_type varchar(255),
    is_ongoing boolean,
    event_type varchar(255),
    mode varchar(255),
    owner_operator_id smallint,
    vehicle_number integer,
    unique_vehicle_id varchar(255),
    route_id varchar(255),
    direction_id smallint,
    headsign varchar(255),
    journey_start_time time,
    next_stop_id varchar(255),
    geohash_level smallint,
    topic_latitude double precision,
    topic_longitude double precision,
    desi varchar(255),
    dir smallint,
    oper smallint,
    veh integer,
    tst timestamp with time zone,
    tsi bigint,
    spd double precision,
    hdg smallint,
    lat double precision,
    long double precision,
    acc double precision,
    dl integer,
    odo double precision,
    drst boolean,
    oday date,
    jrn integer,
    line smallint,
    start time,
    loc varchar(255),
    stop integer,
    route varchar(255),
    occu smallint,
    received_at timestamp with time zone,
    uuid uuid,
    seq smallint,
    dr_type smallint,
    version bigint
);

alter table unsignedevent owner to postgres;

create table vehicleposition
(
    id double precision,
    topic_prefix varchar(255),
    topic_version varchar(255),
    journey_type varchar(255),
    is_ongoing boolean,
    event_type varchar(255),
    mode varchar(255),
    owner_operator_id smallint,
    vehicle_number integer,
    unique_vehicle_id varchar(255),
    route_id varchar(255),
    direction_id smallint,
    headsign varchar(255),
    journey_start_time time,
    next_stop_id varchar(255),
    geohash_level smallint,
    topic_latitude double precision,
    topic_longitude double precision,
    desi varchar(255),
    dir smallint,
    oper smallint,
    veh integer,
    tst timestamp with time zone,
    tsi bigint,
    spd double precision,
    hdg smallint,
    lat double precision,
    long double precision,
    acc double precision,
    dl integer,
    odo double precision,
    drst boolean,
    oday date,
    jrn integer,
    line smallint,
    start time,
    loc varchar(255),
    stop integer,
    route varchar(255),
    occu smallint,
    received_at timestamp with time zone,
    uuid uuid,
    seq smallint,
    dr_type smallint,
    version bigint
);

alter table vehicleposition owner to postgres;
