name: Test and create Docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'
      - name: Build with gradle
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload .jar file
        uses: actions/upload-artifact@v3
        with:
          name: transitlog-hfp-importer.jar
          path: build/libs/transitlog-hfp-importer.jar
  publish-dev:
    needs: test
    runs-on: ubuntu-latest
    # Run only on master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Download .jar file
        uses: actions/download-artifact@v2
        with:
          name: transitlog-hfp-importer.jar
          path: build/libs
      - name: Build and publish release Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-hfp-importer
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: dev
  publish-release:
    needs: test
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Download .jar file
        uses: actions/download-artifact@v2
        with:
          name: transitlog-hfp-importer.jar
          path: build/libs
      - name: Add .jar file to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/transitlog-hfp-importer.jar
      - name: Build and publish release Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-hfp-importer
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true